/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single search match result */
export interface SearchMatch {
  /** File path relative to search root */
  filePath: string
  /** Line number (1-indexed) */
  lineNumber: number
  /** Column where match starts (1-indexed) */
  column: number
  /** The full line content */
  lineContent: string
  /** The matched text */
  matchText: string
}
/** Search options */
export interface SearchOptions {
  /** The search pattern (regex or literal) */
  pattern: string
  /** Root directory to search in */
  rootPath: string
  /** Case-insensitive search */
  ignoreCase?: boolean | undefined
  /** Treat pattern as literal (not regex) */
  literal?: boolean | undefined
  /** Maximum number of results */
  maxResults?: number | undefined
  /** File extensions to include (e.g., ["ts", "tsx"]) */
  includeExtensions?: string[] | undefined
  /** Respect .gitignore patterns (default: true) */
  respectGitignore?: boolean | undefined
}
/**
 * Search for a pattern across files in a directory.
 * Respects .gitignore automatically. Runs asynchronously off the main thread.
 */
export declare function searchFiles(options: SearchOptions): Array<SearchMatch>
/**
 * Quick search that returns just file paths matching a pattern.
 * Useful for "find file" use cases.
 */
export declare function searchFileNames(pattern: string, rootPath: string, respectGitignore?: boolean | undefined | null): Array<string>
/** Health check function to verify native module is loaded */
export declare function nativeHealthCheck(): string
/** Get version of the native module */
export declare function nativeVersion(): string
